import Head from "next/head";
import Banner from "../components/Landing/Banner";
import Mission from "../components/Landing/Mission";
import Quote from "../components/Landing/Quote";
import Categories from "../components/Landing/Categories";
import OBOG from "../components/Landing/OBOG";
import Statistical from "../components/Landing/Statistical";
import Story from "../components/Landing/Story";
import Script from "next/script";

export default function Home() {
  return (
    <div>
      <Head>
        <title>DONGDU PRORJECT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          media="all"
          rel="stylesheet"
          href="css/fonts/icomoon/icomoon.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css"
        />

        <link media="all" rel="stylesheet" href="/css/landing.css" />
        {/*eslint-disable */}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
        <script src="/js/isotope/isotope.pkgd.min.js"></script>
        <script src="/js/isotope/packery-mode.pkgd.js"></script>
        <script src="https://unpkg.com/counterup2@2.0.2/dist/index.js"></script>
        {/* eslint-enable */}
      </Head>

      <main>
        <Banner />
        <div className="content-wrapper">
          <Mission />

          <Quote />

          <Categories />
          <Story />
          <section id="sectionId">
            <OBOG />
          </section>

          <Statistical />
        </div>
      </main>
    </div>
  );
}
